sudo: required
services:
  - docker
env:                           
  global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1 
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

  - gcloud config set project  multi-k8s-264121               ##########   project id 259
  - gcloud config set compute/zone us-central1-a 	        ##########    select zone 
  - gcloud container clusters get-credentials  multi-cluster 	###########   name cluster     
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  
  - docker build -t ahmedfarouk141414/react-test -f ./client/Dockerfile.dev ./client  
script:
  - docker run -e CI=true ahmedfarouk141414/react-test npm test -- --coverage  
deploy:
  provider: script                                           #####262
  script: bash ./deploy.sh
  on:
    branch: master
